services:
  switchbot-influxdb:
    container_name: switchbot-influxdb
    build: .
    environment:
      - SWITCHBOT_API_TOKEN=${SWITCHBOT_API_TOKEN}
      - SWITCHBOT_SECRET=${SWITCHBOT_SECRET}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    volumes:
      - ./config:/app/config
      - ./influxdb:/app/influxdb
      - ./switchbot:/app/switchbot
